### ISSUE TITLE
Implement the fastest Livereload available

### ISSUE THREAD

**Issue by 0xrafasec** [caiovaccaro/harplyss#1]
What are your plan about using livereload?

[pt-br] Falei em inglês pois não sabia o que pretende do projeto. O que pensa sobre o Livereload? Pretende usar o que?

**Comment by caiovaccaro** [comment]
Hey, I think that less dependencies is best. So we need to research/test livereload libs and implement the fastest one.

The most we can do without task managers or bloated dependencies is the best.

Any thoughts?

*valeu ;)

**Comment by 0xrafasec** [comment]
I only tested grunt calling livereload. What do you think about the end of this discussion? https://github.com/sintaxi/harp/issues/80

Maybe we can follow this.

**Comment by caiovaccaro** [comment]
Sweet!

I've tried the .sh solution before and had some problems (not only me) so I guess it is not the way to go.

The best would be this: https://github.com/sintaxi/harp/issues/80#issuecomment-49451316

Or: https://www.npmjs.com/package/instant

**Comment by caiovaccaro** [comment]
Thanks to @gabrielgodoy we will test browser-sync, with his pull request https://github.com/caiovaccaro/harplyss/pull/7

I still want to test https://www.npmjs.com/package/instant

**Comment by caiovaccaro** [comment]
Browsersync implemented by @gabrielgodoy in: https://github.com/caiovaccaro/harplyss/tree/feature/browsersync

Instant to be implemented in (pull request should be done to it): https://github.com/caiovaccaro/harplyss/tree/feature/instant

@rafagomes

**Comment by 0xrafasec** [comment]
@caiovaccaro I think we can go with browser-sync. It's working preety good.

**Comment by caiovaccaro** [comment]
Can we disable the sync between open browsers?

**Comment by 0xrafasec** [comment]
Didn't find anything to allows us to do that. I don't like to be mandatory open the page on npm start too. Maybe we can develop this as a parameter. What do you think? If you found something about disable browser sync between browsers, let me know.
